### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by tao123322** [Vision-CAIR/RelTransformer#2]
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL Error 1: unhandled cuda error
Aborted (core dumped)

**Comment by tao123322** [comment]
请问大家是什么原因呢

**Comment by junchen14** [comment]
how many GPUs do you use?

**Comment by tao123322** [comment]
2



---Original---
From: "Jun ***@***.***&gt;
Date: Wed, Sep 22, 2021 15:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Vision-CAIR/RelTransformer] cuda (#2)




 
how many GPUs do you use?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by junchen14** [comment]
the code is configured with 8 gpus. You need to modify the code to fit in 2-gpus environment

**Comment by tao123322** [comment]
Below is the detailed information of the GPU I used.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vision-CAIR/RelTransformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vision-CAIR/RelTransformer] cuda (#2)





 
how many GPUs do you use?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tao123322** [comment]
Can you tell me which folders need to be configured？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vision-CAIR/RelTransformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vision-CAIR/RelTransformer] cuda (#2)





 
the code is configured with 8 gpus. You need to modify the code to fit in 2-gpus environment
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by junchen14** [comment]
you should start to modify from the file
tools/train_net_reltransformer.py

**Comment by tao123322** [comment]
Teacher, I just started this direction, can you give me a specific modification plan? So I can learn better.Thank you very much teacher!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vision-CAIR/RelTransformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vision-CAIR/RelTransformer] cuda (#2)





 
you should start to modify from the file
 tools/train_net_reltransformer.py
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
